blog/urls.py
from django.urls import path
from .views import render_posts, post_detail


app_name = 'blog'

urlpatterns = [
    path('',render_posts,name='posts'),
    path('<int:post_id>',post_detail,name='post_detail')
    ]

django_portfolio/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/',include('blog.urls'), name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100) 
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images/')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
import markdown

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.description = markdown.markdown(post.description)  # Convertir Markdown a HTML
    return render(request, 'post_detail.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from .models import Project
#en django cualquier carpeta que se llame templates va a poder ser accesidad por el metodo render

def home(request):
    projects = Project.objects.all()
    return render(request,'home.html',{'projects':projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}
    <div class="text-center">
        <h1>{{ post.title }}</h1>
        <h3 class="my-2 h5 text-muted">{{ post.published_date }}</h3>  <!-- Cambié 'date' a 'published_date' -->
        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
        <div class="my-4">
            <p>{{ post.description | safe }}</p>  <!-- Muestra la descripción si la necesitas -->
        </div>
        <div class="my-4">
            <!-- Renderiza el contenido en Markdown convertido a HTML -->
            <div>{{ post.content | safe }}</div>
        </div>
    </div>
{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Posts</h1>

    {% for post in posts%}

        <div class="p-3">
            <div class="card card-body text-bg-dark p-3">
                <div class="row">
                    <div class="col-3">
                        <img src="{{post.image.url}}" alt="{{ post.title }}" class="img-fluid">
                    </div>
                    <div class="col-9">
                        <h2>{{ post.title }}</h2>    
                        <h3 class="position-absolute top-0 end-0 my-2 text-muted">{{ post.date |date:'d m Y' }}</h3>
                        <p>{{ post.description|striptags|truncatechars:100 }}</p>
                        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-info">{{post.title}}</a>
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}
  {% load static %}
  
  <div class="container text-left bg-black my-auto align-left">
      <header class="row bg-black">
          <div class="row align-left">
              <div class="col-4 align-left">
                <img class="align-left" src="{% static 'portfolio/webpage.jpeg' %}" alt="">
              </div>

              <div class="col-8 align-center text-justify">
                <h1>I am Julio Donadello</h1>
                <h3>I am a Python Machine Learning Engineer</h3>                  
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aspernatur quo, consequuntur minus voluptate quod voluptas odio illo, iure porro, accusantium eaque beatae! Eveniet debitis expedita eum quidem atque neque, hic quo possimus iure, veniam, mollitia voluptatibus. Recusandae hic maxime, suscipit laboriosam, in possimus, quia aperiam animi vero quisquam pariatur ab fugit dolor doloribus. Harum animi vitae unde nihil assumenda soluta ipsam sapiente possimus optio maiores, sequi vel quaerat repellat aliquam in facilis reprehenderit quibusdam quia voluptatum enim est, incidunt similique! Totam laborum animi, minima vero odio illum alias debitis consequuntur? Provident quos tenetur temporibus! Fugiat omnis officiis sed animi libero.</p>
                <a href="{% static 'portfolio/cvJulioDonadello.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3" target="_blank">Download CV</a>                 
              </div>
              
          </div>
      </header>
    </div>

  
  <div class="row my-4 text-center">
    <h3>My Projects</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, ab! In dolores cupiditate accusantium facilis!</p>
    {% for project in projects  %}
      <div class="col-md-4 p-4">
        <div class="card-bg-black card-project">
          <img src="{{project.image.url}}" alt="{{project.title}}" class='card-img-top'>
          <div class="card-body">
            <h2 style="background-color: #990099;">{{ project.title }}</h2>
            <p style="color: #670d0d;background-color:rgb(173, 236, 91)">{{ project.description }}</p>
            <br>     
            {% if project.url %}
              <a href="{{project.url}}" class='btn btn-light rounded-4 btn-sm' target='_blank'>{{project.url}} </a>
            {%endif%}
            <br>
          </div>
        </div> 
      </div>
    {% endfor %}

    </div>    

{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    {% include 'partials/_navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

portfolio/templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">JAD</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cvJulioDonadello.pdf' %}" target="_blank">Download CV</a>
          </li>
        </ul>
      </div>
    </div>
</nav>